/**
 * transform.ts 手算测试（resample + report）。
 */
import assert from 'node:assert/strict'
import { test } from 'node:test'
import { generateReport, resampleCandles } from '../src/transform.ts'

const candles = Array.from({ length: 10 }, (_, i) => ({
  openTime: (i + 1) * 1000,
  open: 10 + i,
  high: 12 + i,
  low: 9 + i,
  close: 11 + i,
  volume: 100 + i,
}))

test('resampleCandles: 周线聚合（7 根满桶 + 3 根尾桶）', () => {
  const out = resampleCandles(candles, 'week')
  assert.equal(out.length, 2)
  // 桶 1：bar 0-6
  assert.equal(out[0]!.openTime, 1000)
  assert.equal(out[0]!.open, 10)
  assert.equal(out[0]!.high, 18)   // 12+6
  assert.equal(out[0]!.low, 9)
  assert.equal(out[0]!.close, 17)  // 11+6
  assert.equal(out[0]!.volume, 100 + 101 + 102 + 103 + 104 + 105 + 106)
  assert.equal(out[0]!.bars, 7)
  // 桶 2：bar 7-9
  assert.equal(out[1]!.openTime, 8000)
  assert.equal(out[1]!.close, 20)
  assert.equal(out[1]!.bars, 3)
})

test('resampleCandles: 月线（30 根全在一桶）', () => {
  const out = resampleCandles(candles, 'month')
  assert.equal(out.length, 1)
  assert.equal(out[0]!.bars, 10)
  assert.equal(out[0]!.high, 21)
  assert.equal(out[0]!.low, 9)
})

test('resampleCandles: 空输入', () => {
  assert.deepEqual(resampleCandles([], 'week'), [])
})

test('generateReport: 报告含全部模块段落', () => {
  const report = generateReport({
    strategy: 'dual-MA crossover (5/20)',
    metrics: { totalReturnPct: -0.6, maxDrawdownPct: 6.07, sharpe: -0.045, annualizedVol: 32.03, calmar: -0.3, sortino: -0.024, winRate: 12.6, profitFactor: 0.996 },
    risk: { var95: 0.0292, cvar95: 0.0417, maxDrawdownPct: 28.69, beta: 0, informationRatio: -1.343, trackingError: 32.03 },
    factor: { ic: -0.0528, icir: -1.258 },
    fund: { initialCapital: 100_000_000, finalNavNet: 0.9816, finalAum: 98_160_000, netReturnPct: -1.84, managementFeeTotal: 400_000, performanceFeeTotal: 0 },
  })
  assert.match(report, /# Quant Research Report/)
  assert.match(report, /## Strategy/)
  assert.match(report, /dual-MA crossover/)
  assert.match(report, /## Performance/)
  assert.match(report, /Total Return: \*\*-0.600%\*\*/)
  assert.match(report, /## Risk/)
  assert.match(report, /VaR \(95%\): \*\*2.92%\*\*/)
  assert.match(report, /## Factor/)
  assert.match(report, /IC: -0.0528/)
  assert.match(report, /## Fund Simulation/)
  assert.match(report, /Final NAV: \*\*0.9816\*\*/)
})

test('generateReport: 空输入最小报告', () => {
  const report = generateReport({})
  assert.match(report, /# Quant Research Report/)
  assert.match(report, /Generated by dsh-quant/)
  assert.doesNotMatch(report, /## Strategy/)
})
