/**
 * 数据转换（纯函数、零依赖）：周期聚合（resample）与研究报告生成。
 */

export interface SourceCandle {
  openTime: number
  open: number
  high: number
  low: number
  close: number
  volume: number
}

export interface AggregatedCandle {
  /** 周期首根的开盘时间 */
  openTime: number
  open: number
  high: number
  low: number
  close: number
  volume: number
  /** 该周期包含的原始根数 */
  bars: number
}

export type ResamplePeriod = 'week' | 'month'

const PERIOD_BARS: Record<ResamplePeriod, number> = { week: 7, month: 30 }

/**
 * K 线周期聚合：按固定根数分桶（week=7、month=30），适用于 7×24 市场
 * （crypto）；A 股交易日历需外部传入桶边界（数据适配原则）。
 * 尾部不足一桶按实际根数聚合。
 */
export function resampleCandles(candles: readonly SourceCandle[], period: ResamplePeriod): AggregatedCandle[] {
  const bars = PERIOD_BARS[period]
  const out: AggregatedCandle[] = []
  for (let start = 0; start < candles.length; start += bars) {
    const bucket = candles.slice(start, start + bars)
    if (bucket.length === 0) continue
    let high = -Infinity
    let low = Infinity
    let volume = 0
    for (const c of bucket) {
      if (c.high > high) high = c.high
      if (c.low < low) low = c.low
      volume += c.volume
    }
    out.push({
      openTime: bucket[0]!.openTime,
      open: bucket[0]!.open,
      high,
      low,
      close: bucket[bucket.length - 1]!.close,
      volume,
      bars: bucket.length,
    })
  }
  return out
}

export interface ReportInput {
  strategy?: string
  metrics?: Record<string, number | null>
  risk?: {
    var95: number
    cvar95: number
    maxDrawdownPct: number
    beta: number
    informationRatio: number
    trackingError: number
  }
  fund?: {
    initialCapital: number
    finalNavNet: number
    finalAum: number
    netReturnPct: number
    managementFeeTotal: number
    performanceFeeTotal: number
  }
  factor?: { ic: number; icir: number }
}

/** 生成 Markdown 研究报告（把各模块结果组装成可读结论）。 */
export function generateReport(input: ReportInput): string {
  const lines: string[] = ['# Quant Research Report', '']
  if (input.strategy) {
    lines.push(`## Strategy`, '', input.strategy, '')
  }
  if (input.metrics) {
    const m = input.metrics
    const fmt = (v: number | null | undefined, suffix = ''): string =>
      v === null || v === undefined ? 'n/a' : v.toFixed(3) + suffix
    lines.push(
      '## Performance',
      '',
      `- Total Return: **${fmt(m.totalReturnPct, '%')}**`,
      `- Max Drawdown: **${fmt(m.maxDrawdownPct, '%')}**`,
      `- Sharpe: **${fmt(m.sharpe)}**`,
      `- Annualized Volatility: ${fmt(m.annualizedVol, '%')}`,
      `- Calmar: ${fmt(m.calmar)} · Sortino: ${fmt(m.sortino)}`,
      `- Win Rate: ${fmt(m.winRate, '%')} · Profit Factor: ${m.profitFactor === null ? '∞' : fmt(m.profitFactor)}`,
      '',
    )
  }
  if (input.risk) {
    const r = input.risk
    lines.push(
      '## Risk',
      '',
      `- VaR (95%): **${(r.var95 * 100).toFixed(2)}%** · CVaR (95%): **${(r.cvar95 * 100).toFixed(2)}%**`,
      `- Max Drawdown: ${r.maxDrawdownPct.toFixed(2)}%`,
      `- Beta: ${r.beta.toFixed(3)} · Information Ratio: ${r.informationRatio.toFixed(3)} · Tracking Error: ${r.trackingError.toFixed(2)}%`,
      '',
    )
  }
  if (input.factor) {
    lines.push(
      '## Factor',
      '',
      `- IC: ${input.factor.ic.toFixed(4)} · ICIR: ${input.factor.icir.toFixed(3)}`,
      '',
    )
  }
  if (input.fund) {
    const f = input.fund
    const yi = (v: number): string => (v / 1e8).toFixed(3) + ' 亿'
    lines.push(
      '## Fund Simulation',
      '',
      `- Initial: ${yi(f.initialCapital)} (NAV 1.00) → Final NAV: **${f.finalNavNet.toFixed(4)}** (AUM ${yi(f.finalAum)})`,
      `- Net Return: **${f.netReturnPct.toFixed(2)}%**`,
      `- Management Fee: ${yi(f.managementFeeTotal)} · Performance Fee: ${yi(f.performanceFeeTotal)}`,
      '',
    )
  }
  lines.push('---', '', '*Generated by dsh-quant.*')
  return lines.join('\n')
}
